---
run:
  # concurrency: 6
  go: "1.23"
  timeout: 2m
  issues-exit-code: 1
  tests: true
linters-settings:
  goheader:
    template-path: ".license/template.txt"
    values:
      regexp:
        company: .*
        copyright-holder: Copyright \(c\) ({{year-range}}) {{company}}\n\n
        copyright-holders: ({{copyright-holder}})+
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    enable:
      - shadow
    settings:
      printf:
        funcs:
          - (github.com/sirupsen/logrus.FieldLogger).Infof
          - (github.com/sirupsen/logrus.FieldLogger).Warnf
          - (github.com/sirupsen/logrus.FieldLogger).Errorf
          - (github.com/sirupsen/logrus.FieldLogger).Fatalf
  goimports:
    local-prefixes: github.com/networkservicemesh
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 150
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    rules:
      main:
        deny:
          - pkg: errors
            desc: Please use github.com/pkg/errors instead of errors in go imports
  misspell:
    locale: US
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  varnamelen:
    ignore-names:
      - cl
      - m
      - u
      - wg
  gocritic:
    enabled-checks:
      - appendCombine
      - boolExprSimplify
      - builtinShadow
      - commentedOutCode
      - commentedOutImport
      - docStub
      - dupImport
      - emptyFallthrough
      - emptyStringTest
      - equalFold
      - evalOrder
      - hexLiteral
      - hugeParam
      - importShadow
      - indexAlloc
      - initClause
      - methodExprCall
      - nestingReduce
      - nilValReturn
      - octalLiteral
      - paramTypeCombine
      - rangeExprCopy
      - rangeValCopy
      - regexpPattern
      - stringXbytes
      - typeAssertChain
      - typeUnparen
      - unlabelStmt
      - unnamedResult
      - unnecessaryBlock
      - weakCond
      - yodaStyleExpr
linters:
  enable-all: true
  disable:
    - execinquery # The linter 'execinquery' is deprecated (since v1.58.0) due to: The repository of the linter has been archived by the owner.
    - exportloopref # The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
    - paralleltest # t.Parallel() adds on test run stage if required
    - gci # It conflicts with goimports

    # New linters, that were not enabled or/either were not created on older linter version.
    - testpackage
    - thelper
    - intrange
    - exhaustruct
    - nlreturn
    - nonamedreturns
    - wsl
    - varnamelen
    - ireturn
    - gomnd
    - containedctx
    - mnd
    - lll
    - gofumpt
    - godox
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
