---
name: Docker push ghcr

on:
  push:
    branches: [main]
jobs:
  push:
    if: ${{ github.repository != 'networkservicemesh/cmd-template' && (github.event.workflow_run.conclusion == 'success' && github.actor == 'nsmbot' || github.event_name == 'push') }}
    uses: networkservicemesh/.github/.github/workflows/docker-push-ghcr.yaml@main
